basePath: /api/v1
definitions:
  main.healthResponse:
    properties:
      api_version:
        type: string
      environment:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact:
    email: digitalmarketfy@gmail.com
    name: Puremike
    url: http://github.com/puremike
  description: This is an API for a Courier Delivery System
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Courier Delivery System API
  version: 1.1.0
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Returns the status of the application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.healthResponse'
      summary: Get health
      tags:
      - health
swagger: "2.0"
